name: CI
on:
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.15'
    - name: test
      run: |
        echo $GOPATH
        git clone https://github.com/kordamp/gm
        cd gm
        make
        ./gm -gv
      env:
        GOPATH: /home/runner/work/actions-playground/go
