name: CI
on:
  push:
  workflow_dispatch:
jobs:
  a:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: ls -la
  b:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: ls -la
  c:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: ls -la
  a1:
    runs-on: ubuntu-latest
    needs: [a, b]
    steps:
    - uses: actions/checkout@v2
    - run: ls -la
  a2:
    runs-on: ubuntu-latest
    needs: [a1, c]
    steps:
    - uses: actions/checkout@v2
    - run: ls -la