name: CI
on:
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: test
      run: |
        git clone https://github.com/kordamp/gm
        cd gm
        make
        ./gm -gv
